<?php
function strip_html_tags($text)
	{
		$text = preg_replace(
		    array(
		      // Remove invisible content
		        '@<html[^>]*?>.*?</html>@siu',
		        '@<head[^>]*?>.*?</head>@siu',
		        '@<body[^>]*?>.*?</body>@siu',
		        '@<style[^>]*?>.*?</style>@siu',
		        '@<script[^>]*?.*?</script>@siu',
		        '@<object[^>]*?.*?</object>@siu',
		        '@<embed[^>]*?.*?</embed>@siu',
		        '@<applet[^>]*?.*?</applet>@siu',
		        '@<noframes[^>]*?.*?</noframes>@siu',
		        '@<noscript[^>]*?.*?</noscript>@siu',
		        '@<noembed[^>]*?.*?</noembed>@siu',
		      // Add line breaks before and after blocks
		        '@</?((address)|(blockquote)|(center)|(del))@iu',
		        '@</?((div)|(h[1-9])|(ins)|(isindex)|(p)|(pre))@iu',
		        '@</?((dir)|(dl)|(dt)|(dd)|(li)|(menu)|(ol)|(ul))@iu',
		        '@</?((table)|(th)|(td)|(caption))@iu',
		        '@</?((form)|(button)|(fieldset)|(legend)|(input))@iu',
		        '@</?((label)|(select)|(optgroup)|(option)|(textarea))@iu',
		        '@</?((frameset)|(frame)|(iframe))@iu',
		    ),
		    array(
		        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
		        "\n\$0", "\n\$0", "\n\$0", "\n\$0", "\n\$0", "\n\$0",
		        "\n\$0", "\n\$0",
		    ),
		    $text);
		
		$text = preg_replace(
			array(
				'/(<[^>]+) script=".*?"/i',
				'/(<[^>]+) onafterprint=".*?"/i',
				'/(<[^>]+) onbeforeprint=".*?"/i',
				'/(<[^>]+) onbeforeunload=".*?"/i',
				'/(<[^>]+) onerror=".*?"/i',
				'/(<[^>]+) onhashchange=".*?"/i',
				'/(<[^>]+) onload=".*?"/i',
				'/(<[^>]+) onoffline=".*?"/i',
				'/(<[^>]+) ononline=".*?"/i',
				'/(<[^>]+) onpagehide=".*?"/i',
				'/(<[^>]+) onpageshow=".*?"/i',
				'/(<[^>]+) onpopstate=".*?"/i',
				'/(<[^>]+) onresize=".*?"/i',
				'/(<[^>]+) onstorage=".*?"/i',
				'/(<[^>]+) onunload=".*?"/i',
				'/(<[^>]+) onblur=".*?"/i',
				'/(<[^>]+) onchange=".*?"/i',
				'/(<[^>]+) oncontextmenu=".*?"/i',
				'/(<[^>]+) onfocus=".*?"/i',
				'/(<[^>]+) oninput=".*?"/i',
				'/(<[^>]+) oninvalid=".*?"/i',
				'/(<[^>]+) onreset=".*?"/i',
				'/(<[^>]+) onsearch=".*?"/i',
				'/(<[^>]+) onselect=".*?"/i',
				'/(<[^>]+) onsubmit=".*?"/i',
				'/(<[^>]+) onkeydown=".*?"/i',
				'/(<[^>]+) onkeypress=".*?"/i',
				'/(<[^>]+) onkeyup=".*?"/i',
				'/(<[^>]+) onclick=".*?"/i',
				'/(<[^>]+) ondblclick=".*?"/i',
				'/(<[^>]+) ondrag=".*?"/i',
				'/(<[^>]+) ondragend=".*?"/i',
				'/(<[^>]+) ondragenter=".*?"/i',
				'/(<[^>]+) ondragleave=".*?"/i',
				'/(<[^>]+) ondragover=".*?"/i',
				'/(<[^>]+) ondragstart=".*?"/i',
				'/(<[^>]+) ondrop=".*?"/i',
				'/(<[^>]+) onmousedown=".*?"/i',
				'/(<[^>]+) onmousemove=".*?"/i',
				'/(<[^>]+) onmouseout=".*?"/i',
				'/(<[^>]+) onmouseover=".*?"/i',
				'/(<[^>]+) onmouseup=".*?"/i',
				'/(<[^>]+) onmousewheel=".*?"/i',
				'/(<[^>]+) onscroll=".*?"/i',
				'/(<[^>]+) onwheel=".*?"/i',
				'/(<[^>]+) oncopy=".*?"/i',
				'/(<[^>]+) oncut=".*?"/i',
				'/(<[^>]+) onpaste=".*?"/i',
				'/(<[^>]+) onabort=".*?"/i',
				'/(<[^>]+) oncanplay=".*?"/i',
				'/(<[^>]+) oncanplaythrough=".*?"/i',
				'/(<[^>]+) oncuechange=".*?"/i',
				'/(<[^>]+) ondurationchange=".*?"/i',
				'/(<[^>]+) onemptied=".*?"/i',
				'/(<[^>]+) onended=".*?"/i',
				'/(<[^>]+) onloadeddata=".*?"/i',
				'/(<[^>]+) onloadedmetadata=".*?"/i',
				'/(<[^>]+) onloadstart=".*?"/i',
				'/(<[^>]+) onpause=".*?"/i',
				'/(<[^>]+) onplay=".*?"/i',
				'/(<[^>]+) onplaying=".*?"/i',
				'/(<[^>]+) onprogress=".*?"/i',
				'/(<[^>]+) onratechange=".*?"/i',
				'/(<[^>]+) onseeked=".*?"/i',
				'/(<[^>]+) onseeking=".*?"/i',
				'/(<[^>]+) onstalled=".*?"/i',
				'/(<[^>]+) onsuspend=".*?"/i',
				'/(<[^>]+) ontimeupdate=".*?"/i',
				'/(<[^>]+) onvolumechange=".*?"/i',
				'/(<[^>]+) onwaiting=".*?"/i',
				'/(<[^>]+) onshow=".*?"/i',
				'/(<[^>]+) ontoggle=".*?"/i',
				'/(<[^>]+) script=\'.*?\'/i',
				'/(<[^>]+) onafterprint=\'.*?\'/i',
				'/(<[^>]+) onbeforeprint=\'.*?\'/i',
				'/(<[^>]+) onbeforeunload=\'.*?\'/i',
				'/(<[^>]+) onerror=\'.*?\'/i',
				'/(<[^>]+) onhashchange=\'.*?\'/i',
				'/(<[^>]+) onload=\'.*?\'/i',
				'/(<[^>]+) onoffline=\'.*?\'/i',
				'/(<[^>]+) ononline=\'.*?\'/i',
				'/(<[^>]+) onpagehide=\'.*?\'/i',
				'/(<[^>]+) onpageshow=\'.*?\'/i',
				'/(<[^>]+) onpopstate=\'.*?\'/i',
				'/(<[^>]+) onresize=\'.*?\'/i',
				'/(<[^>]+) onstorage=\'.*?\'/i',
				'/(<[^>]+) onunload=\'.*?\'/i',
				'/(<[^>]+) onblur=\'.*?\'/i',
				'/(<[^>]+) onchange=\'.*?\'/i',
				'/(<[^>]+) oncontextmenu=\'.*?\'/i',
				'/(<[^>]+) onfocus=\'.*?\'/i',
				'/(<[^>]+) oninput=\'.*?\'/i',
				'/(<[^>]+) oninvalid=\'.*?\'/i',
				'/(<[^>]+) onreset=\'.*?\'/i',
				'/(<[^>]+) onsearch=\'.*?\'/i',
				'/(<[^>]+) onselect=\'.*?\'/i',
				'/(<[^>]+) onsubmit=\'.*?\'/i',
				'/(<[^>]+) onkeydown=\'.*?\'/i',
				'/(<[^>]+) onkeypress=\'.*?\'/i',
				'/(<[^>]+) onkeyup=\'.*?\'/i',
				'/(<[^>]+) onclick=\'.*?\'/i',
				'/(<[^>]+) ondblclick=\'.*?\'/i',
				'/(<[^>]+) ondrag=\'.*?\'/i',
				'/(<[^>]+) ondragend=\'.*?\'/i',
				'/(<[^>]+) ondragenter=\'.*?\'/i',
				'/(<[^>]+) ondragleave=\'.*?\'/i',
				'/(<[^>]+) ondragover=\'.*?\'/i',
				'/(<[^>]+) ondragstart=\'.*?\'/i',
				'/(<[^>]+) ondrop=\'.*?\'/i',
				'/(<[^>]+) onmousedown=\'.*?\'/i',
				'/(<[^>]+) onmousemove=\'.*?\'/i',
				'/(<[^>]+) onmouseout=\'.*?\'/i',
				'/(<[^>]+) onmouseover=\'.*?\'/i',
				'/(<[^>]+) onmouseup=\'.*?\'/i',
				'/(<[^>]+) onmousewheel=\'.*?\'/i',
				'/(<[^>]+) onscroll=\'.*?\'/i',
				'/(<[^>]+) onwheel=\'.*?\'/i',
				'/(<[^>]+) oncopy=\'.*?\'/i',
				'/(<[^>]+) oncut=\'.*?\'/i',
				'/(<[^>]+) onpaste=\'.*?\'/i',
				'/(<[^>]+) onabort=\'.*?\'/i',
				'/(<[^>]+) oncanplay=\'.*?\'/i',
				'/(<[^>]+) oncanplaythrough=\'.*?\'/i',
				'/(<[^>]+) oncuechange=\'.*?\'/i',
				'/(<[^>]+) ondurationchange=\'.*?\'/i',
				'/(<[^>]+) onemptied=\'.*?\'/i',
				'/(<[^>]+) onended=\'.*?\'/i',
				'/(<[^>]+) onloadeddata=\'.*?\'/i',
				'/(<[^>]+) onloadedmetadata=\'.*?\'/i',
				'/(<[^>]+) onloadstart=\'.*?\'/i',
				'/(<[^>]+) onpause=\'.*?\'/i',
				'/(<[^>]+) onplay=\'.*?\'/i',
				'/(<[^>]+) onplaying=\'.*?\'/i',
				'/(<[^>]+) onprogress=\'.*?\'/i',
				'/(<[^>]+) onratechange=\'.*?\'/i',
				'/(<[^>]+) onseeked=\'.*?\'/i',
				'/(<[^>]+) onseeking=\'.*?\'/i',
				'/(<[^>]+) onstalled=\'.*?\'/i',
				'/(<[^>]+) onsuspend=\'.*?\'/i',
				'/(<[^>]+) ontimeupdate=\'.*?\'/i',
				'/(<[^>]+) onvolumechange=\'.*?\'/i',
				'/(<[^>]+) onwaiting=\'.*?\'/i',
				'/(<[^>]+) onshow=\'.*?\'/i',
				'/(<[^>]+) ontoggle=\'.*?\'/i'
			), 
			'$1', 
			$text);
		
		
		return $text;
	}
echo strip_html_tags('<p>SO Tsu! It&#39;s a new pyramid based social network. To get started, sign up and share your link with as many people as you can. They will sign up using your link, and they will become your &quot;Children.&quot; You get a third&nbsp;of the revenue they generate by sharing posts and creating content.&nbsp;Your children will then share their link. People will sign up under them, and they will become your &quot;Grandchildren.&quot; You get a third of a third of what the grandchildren make. .&nbsp;</p>

<p><img alt="" src="http://i.imgur.com/kM41ert.png" style="float:right; height:250px; width:400px" /></p>

<p><a href="https://www.tsu.co/DanaAyles">https://www.tsu.co/DanaAyles</a></p>

<iframe width="560" height="315" onload="alert(\'test\');" src="https://www.youtube.com/embed/cnaDU4cmDBQ" frameborder="0" allowfullscreen></iframe>');
?>